### get person list
GET http://localhost:3001/api/persons

### get info
GET http://localhost:3001/info

### get person exist
GET http://localhost:3001/api/persons/4

### get person not exist
GET http://localhost:3001/api/persons/5

### delete person exist
DELETE http://localhost:3001/api/persons/4

### delete person not exist
DELETE http://localhost:3001/api/persons/5

### add new person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name":"Zhang san",
  "number":"123456"
}

### add new person with empty number
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name":"Zhang san",
  "number":""
}
